[package]
name = "day23"
version = "0.1.0"
edition = "2021"

[dependencies]
global = {path = "../global"}
regex = "1"
num = "0.4.0"
priority-queue = "1.3.0"
parse-display = "0.8.0"

[[bin]]
name = "day23a"

[[bin]]
name = "day23b"