[package]
name = "day15"
version = "0.1.0"
edition = "2021"

[dependencies]
global = {path = "../global"}
regex = "1"
num = "0.4.0"
priority-queue = "1.3.0"

[[bin]]
name = "day15a"

[[bin]]
name = "day15b"